"""empty message

Revision ID: 02392188a3a2
Revises: 277bd151b99d
Create Date: 2021-07-05 14:22:44.969742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02392188a3a2'
down_revision = '277bd151b99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify_status', sa.Enum('stranger', 'mail', 'basic', 'scard', 'admin'), server_default='stranger', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify_status')
    # ### end Alembic commands ###
