"""empty message

Revision ID: 0a6cea7835c0
Revises: 9c29c8b1b951
Create Date: 2021-07-10 04:41:23.047621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6cea7835c0'
down_revision = '9c29c8b1b951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('channel_index', table_name='subscribe')
    op.create_index('channel_user_index', 'subscribe', ['channel_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('channel_user_index', table_name='subscribe')
    op.create_index('channel_index', 'subscribe', ['channel_id'], unique=False)
    # ### end Alembic commands ###
