"""empty message

Revision ID: 277bd151b99d
Revises: fac12a16ac68
Create Date: 2021-07-05 02:28:00.738261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277bd151b99d'
down_revision = 'fac12a16ac68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('href', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'href')
    # ### end Alembic commands ###
