"""empty message

Revision ID: 33807a950b50
Revises: 7d87e7f3082d
Create Date: 2021-07-20 03:54:01.308434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33807a950b50'
down_revision = '7d87e7f3082d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'postboard', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
