"""empty message

Revision ID: 3ce97997bcc0
Revises: 9a90def79f65
Create Date: 2021-05-19 22:40:14.024081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce97997bcc0'
down_revision = '9a90def79f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('course', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('interest', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('swap', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('want_to_try', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('worry', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'worry')
    op.drop_column('user', 'want_to_try')
    op.drop_column('user', 'swap')
    op.drop_column('user', 'interest')
    op.drop_column('user', 'course')
    op.drop_column('user', 'country')
    op.drop_column('user', 'club')
    # ### end Alembic commands ###
