"""empty message

Revision ID: 44e45369770c
Revises: 
Create Date: 2021-06-12 14:08:33.017959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e45369770c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('verify', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('collage', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('scard', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('avatar', sa.String(length=255), server_default='https://d2lzngk4bddvz9.cloudfront.net/avatar/default_avatar.jpeg', nullable=True),
    sa.Column('relationship', sa.Enum('secret', 'single', 'in_a_relationship', 'complicated', 'open_relationship', 'no_show'), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('club', sa.Text(), nullable=True),
    sa.Column('course', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('worry', sa.Text(), nullable=True),
    sa.Column('swap', sa.Text(), nullable=True),
    sa.Column('want_to_try', sa.Text(), nullable=True),
    sa.Column('days_no_open_scard', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('match_list', sa.JSON(), server_default=sa.text('(JSON_ARRAY())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('email_pwd_index', 'user', ['email', 'password'], unique=False)
    op.create_index('no_open_index', 'user', ['days_no_open_scard'], unique=False)
    op.create_table('scard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), server_default=sa.text('(NOW())'), nullable=True),
    sa.Column('user_1_message', sa.String(length=255), nullable=True),
    sa.Column('user_2_message', sa.String(length=255), nullable=True),
    sa.Column('is_friend', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user1_date_index', 'scard', ['user_1', 'create_date'], unique=False)
    op.create_index('user2_date_index', 'scard', ['user_2', 'create_date'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scard_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['scard_id'], ['scard.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index('user2_date_index', table_name='scard')
    op.drop_index('user1_date_index', table_name='scard')
    op.drop_table('scard')
    op.drop_index('no_open_index', table_name='user')
    op.drop_index('email_pwd_index', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
