"""empty message

Revision ID: 4684b716edd6
Revises: d3c231b50bdb
Create Date: 2021-07-05 01:28:04.506069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4684b716edd6'
down_revision = 'd3c231b50bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_user_follow', sa.Column('note_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'post_user_follow', 'notification', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_user_follow', type_='foreignkey')
    op.drop_column('post_user_follow', 'note_id')
    # ### end Alembic commands ###
