"""empty message

Revision ID: 47d4eda35d4b
Revises: 03d68bbfdcac
Create Date: 2021-06-25 20:41:28.876958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d4eda35d4b'
down_revision = '03d68bbfdcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_user_like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('post_user_index', 'post_user_like', ['post_id', 'user_id'], unique=False)
    op.create_table('comment_user_like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comment_user_index', 'comment_user_like', ['comment_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('comment_user_index', table_name='comment_user_like')
    op.drop_table('comment_user_like')
    op.drop_index('post_user_index', table_name='post_user_like')
    op.drop_table('post_user_like')
    # ### end Alembic commands ###
