"""empty message

Revision ID: 481f9e472a6b
Revises: f164cd215772
Create Date: 2021-05-20 02:28:35.566532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481f9e472a6b'
down_revision = 'f164cd215772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('relationship', sa.Enum('secret', 'single', 'in_a_relationship', 'complicated', 'open_relationship'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'relationship')
    # ### end Alembic commands ###
