"""empty message

Revision ID: 5213ebbd0575
Revises: 7220233fe5bd
Create Date: 2021-06-10 00:07:23.909417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5213ebbd0575'
down_revision = '7220233fe5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('match_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'match_list')
    # ### end Alembic commands ###
