"""empty message

Revision ID: 54cdaa6f1029
Revises: 5be93fdaf212
Create Date: 2021-07-04 00:01:36.431362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54cdaa6f1029'
down_revision = '5be93fdaf212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_cmt_index', table_name='comment_user_like')
    op.create_foreign_key(None, 'comment_user_like', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_user_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'followers')
    op.create_foreign_key(None, 'post_user_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_user_like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_user_like', type_='foreignkey')
    op.drop_constraint(None, 'post_user_like', type_='foreignkey')
    op.add_column('post', sa.Column('followers', mysql.JSON(), server_default=sa.text('(json_array())'), nullable=True))
    op.drop_constraint(None, 'comment_user_like', type_='foreignkey')
    op.drop_constraint(None, 'comment_user_like', type_='foreignkey')
    op.create_index('user_cmt_index', 'comment_user_like', ['user_id', 'comment_id'], unique=False)
    # ### end Alembic commands ###
