"""empty message

Revision ID: 5b60347b0857
Revises: be01053e873f
Create Date: 2021-06-10 00:28:37.423411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b60347b0857'
down_revision = 'be01053e873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('match_list', sa.JSON(), nullable=True))
    op.drop_column('user', 'scard_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scard_list', mysql.JSON(), nullable=True))
    op.drop_column('user', 'match_list')
    # ### end Alembic commands ###
