"""empty message

Revision ID: 5be93fdaf212
Revises: 049951329932
Create Date: 2021-07-03 23:43:39.538705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be93fdaf212'
down_revision = '049951329932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('comment_user_index', table_name='comment_user_like')
    op.create_index('user_cmt_index', 'comment_user_like', ['user_id', 'comment_id'], unique=False)
    op.drop_index('post_user_index', table_name='post_user_like')
    op.create_index('user_post_index', 'post_user_like', ['user_id', 'post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_post_index', table_name='post_user_like')
    op.create_index('post_user_index', 'post_user_like', ['post_id', 'user_id'], unique=False)
    op.drop_index('user_cmt_index', table_name='comment_user_like')
    op.create_index('comment_user_index', 'comment_user_like', ['comment_id', 'user_id'], unique=False)
    # ### end Alembic commands ###
