"""empty message

Revision ID: 7220233fe5bd
Revises: d668fbf72870
Create Date: 2021-06-06 22:33:20.455140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7220233fe5bd'
down_revision = 'd668fbf72870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user1_id_index', table_name='scard')
    op.drop_index('user2_id_index', table_name='scard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user2_id_index', 'scard', ['user_2', 'id'], unique=False)
    op.create_index('user1_id_index', 'scard', ['user_1', 'id'], unique=False)
    # ### end Alembic commands ###
