"""empty message

Revision ID: 74d84c76f6f0
Revises: 7e4c51c189a1
Create Date: 2021-06-06 21:10:37.016319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d84c76f6f0'
down_revision = '7e4c51c189a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'scard', ['scard_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'scard', 'user', ['user_2'], ['id'])
    op.create_foreign_key(None, 'scard', 'user', ['user_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scard', type_='foreignkey')
    op.drop_constraint(None, 'scard', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
