"""empty message

Revision ID: 796bc69b6e57
Revises: 74d84c76f6f0
Create Date: 2021-06-06 22:13:31.114165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796bc69b6e57'
down_revision = '74d84c76f6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user1_id_index', 'scard', ['user_1', 'id'], unique=False)
    op.create_index('user2_id_index', 'scard', ['user_2', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user2_id_index', table_name='scard')
    op.drop_index('user1_id_index', table_name='scard')
    # ### end Alembic commands ###
