"""empty message

Revision ID: 7d87e7f3082d
Revises: e6811ccdc285
Create Date: 2021-07-20 03:52:36.733936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d87e7f3082d'
down_revision = 'e6811ccdc285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postboard', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # op.create_foreign_key(None, 'post', 'postboard', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postboard', 'id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
