"""empty message

Revision ID: 7e4c51c189a1
Revises: a82f85bb92a1
Create Date: 2021-06-05 21:07:34.166840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4c51c189a1'
down_revision = 'a82f85bb92a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user1_date_index', 'scard', ['user_1', 'create_date'], unique=False)
    op.create_index('user2_date_index', 'scard', ['user_2', 'create_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user2_date_index', table_name='scard')
    op.drop_index('user1_date_index', table_name='scard')
    # ### end Alembic commands ###
