"""empty message

Revision ID: 7e653584d315
Revises: 0a6cea7835c0
Create Date: 2021-07-10 13:00:40.603418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e653584d315'
down_revision = '0a6cea7835c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_index', 'subscribe', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_index', table_name='subscribe')
    # ### end Alembic commands ###
