"""empty message

Revision ID: 7fb5bb5283c6
Revises: 1b9ef3f13f7c
Create Date: 2021-05-19 22:27:54.883299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb5bb5283c6'
down_revision = '1b9ef3f13f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('collage', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female'), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'department')
    op.drop_column('user', 'collage')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
