"""empty message

Revision ID: 810e3553d4fa
Revises: f49b7a7cf455
Create Date: 2021-05-19 13:19:03.499742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810e3553d4fa'
down_revision = 'f49b7a7cf455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('verify', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'verify')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
