"""empty message

Revision ID: 8e0bb6a58548
Revises: 80e993127f0a
Create Date: 2021-07-03 17:47:54.315559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0bb6a58548'
down_revision = '80e993127f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('followers', sa.JSON(), server_default=sa.text('(JSON_ARRAY())'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'followers')
    # ### end Alembic commands ###
