"""empty message

Revision ID: 9444f4ded9ee
Revises: 54cdaa6f1029
Create Date: 2021-07-05 01:10:44.872811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9444f4ded9ee'
down_revision = '54cdaa6f1029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('comment_user_index', 'comment_user_like', ['comment_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('comment_user_index', table_name='comment_user_like')
    # ### end Alembic commands ###
