"""empty message

Revision ID: a35087ccec59
Revises: 7e653584d315
Create Date: 2021-07-12 02:19:46.455545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35087ccec59'
down_revision = '7e653584d315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'delete')
    # ### end Alembic commands ###
