"""empty message

Revision ID: a82f85bb92a1
Revises: c988f812a7af
Create Date: 2021-05-27 03:29:56.976969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a82f85bb92a1'
down_revision = 'c988f812a7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'days_no_open_scard',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'days_no_open_scard',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
