"""empty message

Revision ID: b173f0267419
Revises: 2de9749937e4
Create Date: 2021-06-19 17:45:31.882452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b173f0267419'
down_revision = '2de9749937e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postboard', sa.Column('icon', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'postboard', ['icon'])
    op.add_column('user', sa.Column('comment_avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comment_avatar')
    op.drop_constraint(None, 'postboard', type_='unique')
    op.drop_column('postboard', 'icon')
    # ### end Alembic commands ###
