"""empty message

Revision ID: b918ad5e06c9
Revises: 33807a950b50
Create Date: 2021-07-20 05:30:52.761419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b918ad5e06c9'
down_revision = '33807a950b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sys_name', table_name='postboard')
    op.drop_column('postboard', 'sys_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postboard', sa.Column('sys_name', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False))
    op.create_index('sys_name', 'postboard', ['sys_name'], unique=False)
    # ### end Alembic commands ###
