"""empty message

Revision ID: be01053e873f
Revises: 5213ebbd0575
Create Date: 2021-06-10 00:12:31.428120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be01053e873f'
down_revision = '5213ebbd0575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scard_list', sa.JSON(), nullable=True))
    op.drop_column('user', 'match_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('match_list', mysql.JSON(), nullable=True))
    op.drop_column('user', 'scard_list')
    # ### end Alembic commands ###
