"""empty message

Revision ID: c988f812a7af
Revises: 
Create Date: 2021-05-27 03:28:00.511783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c988f812a7af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scard_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('user_1_message', sa.String(length=255), nullable=True),
    sa.Column('user_2_message', sa.String(length=255), nullable=True),
    sa.Column('is_friend', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('collage', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('scard', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.Enum('secret', 'single', 'in_a_relationship', 'complicated', 'open_relationship', 'no_show'), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('club', sa.Text(), nullable=True),
    sa.Column('course', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('worry', sa.Text(), nullable=True),
    sa.Column('swap', sa.Text(), nullable=True),
    sa.Column('want_to_try', sa.Text(), nullable=True),
    sa.Column('days_no_open_scard', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('email_pwd_index', 'user', ['email', 'password'], unique=False)
    op.create_index('no_open_index', 'user', ['days_no_open_scard'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('no_open_index', table_name='user')
    op.drop_index('email_pwd_index', table_name='user')
    op.drop_table('user')
    op.drop_table('scard')
    op.drop_table('messages')
    # ### end Alembic commands ###
