"""empty message

Revision ID: d668fbf72870
Revises: c6f6116d6001
Create Date: 2021-06-06 22:25:16.132903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd668fbf72870'
down_revision = 'c6f6116d6001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_user1_index', table_name='scard')
    op.drop_index('id_user2_index', table_name='scard')
    op.create_index('user1_id_index', 'scard', ['user_1', 'id'], unique=False)
    op.create_index('user2_id_index', 'scard', ['user_2', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user2_id_index', table_name='scard')
    op.drop_index('user1_id_index', table_name='scard')
    op.create_index('id_user2_index', 'scard', ['id', 'user_2'], unique=False)
    op.create_index('id_user1_index', 'scard', ['id', 'user_1'], unique=False)
    # ### end Alembic commands ###
