"""empty message

Revision ID: df87df4065f5
Revises: d14294def29e
Create Date: 2021-07-20 03:42:35.588982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df87df4065f5'
down_revision = 'd14294def29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('postboard', 'id',
    #            existing_type=mysql.INTEGER(),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    print('aa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postboard', 'id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
