"""empty message

Revision ID: e52906fb7a00
Revises: 8d3e51db0c26
Create Date: 2021-05-22 03:38:28.141936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52906fb7a00'
down_revision = '8d3e51db0c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('collage', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('scard', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.Enum('secret', 'single', 'in_a_relationship', 'complicated', 'open_relationship', 'no_show'), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('club', sa.Text(), nullable=True),
    sa.Column('course', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('worry', sa.Text(), nullable=True),
    sa.Column('swap', sa.Text(), nullable=True),
    sa.Column('want_to_try', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
