"""empty message

Revision ID: e6811ccdc285
Revises: fec7b5edfc57
Create Date: 2021-07-20 03:51:02.547906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6811ccdc285'
down_revision = 'fec7b5edfc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.alter_column('post', 'board_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post_ibfk_1', 'post', 'postboard', ['board_id'], ['id'], ondelete='CASCADE')
    op.alter_column('post', 'board_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
