"""empty message

Revision ID: f01ec5458691
Revises: 47d4eda35d4b
Create Date: 2021-06-26 18:42:31.464038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01ec5458691'
down_revision = '47d4eda35d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collage',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collage_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collage_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['collage_id'], ['collage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collage_department')
    op.drop_table('collage')
    # ### end Alembic commands ###
