"""empty message

Revision ID: f164cd215772
Revises: 3ce97997bcc0
Create Date: 2021-05-19 23:31:58.043900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f164cd215772'
down_revision = '3ce97997bcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scard', sa.Boolean(), nullable=True))
    op.alter_column('user', 'verify',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verify',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('user', 'scard')
    # ### end Alembic commands ###
