"""empty message

Revision ID: fac12a16ac68
Revises: 4684b716edd6
Create Date: 2021-07-05 02:11:09.235621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fac12a16ac68'
down_revision = '4684b716edd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('update_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.drop_column('notification', 'updae_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('updae_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_column('notification', 'update_time')
    # ### end Alembic commands ###
